language: android

jdk:
 - oraclejdk8

env: CI=travis

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.3
    - android-24
    - extra-android-m2repository

before_install:
  - TERM=dumb

install:
  - ./gradlew assembleDebug

script:
  - ./gradlew checkDebug

sudo: false
