language: android

jdk:
 - oraclejdk7
 - oraclejdk8

env: CI=travis

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository

before_install:
  - TERM=dumb

install:
  - ./gradlew assembleDebug

script:
  - ./gradlew checkDebug

sudo: false
